---
- name: Set Interface Policy Group Name
  set_fact: 
    interface_policy_group_name: "IPG-AP-{{ link_level_policy }}"

- name: Create Interface Profile
  cisco.aci.aci_rest:
    hostname: "{{ apic_host }}"
    username: "{{ apic_username }}"
    password: "{{ apic_password }}"
    validate_certs: no
    method: post
    path: "/api/mo/uni/infra/funcprof.json"
    content:
      infraAccPortGrp:
        attributes:
          name: "{{ interface_policy_group_name }}"
        children: "{{ interface_policy_group_children }}"