---
- name: Configure Port Single
  hosts: localhost
  gather_facts: no

  vars:
    apic_host: 198.18.133.200
    apic_username: admin
    apic_password: C1sco12345

  roles:
    - name: create_interface_policy_group
    - name: create_interface_selector
    - name: attach_epg
